name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "new submodule"
      - "feat"
  - title: "✨ Enhancements"
    labels:
      - "enhancement"
      - "improvement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "📖 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "🧹 Maintenance"
    labels:
      - "chore"
      - "maintenance"
      - "dependencies"
  - title: "♻️ Refactoring"
    labels:
      - "refactor"
  - title: "🧪 Testing"
    labels:
      - "test"
      - "tests"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "feature"
      - "new submodule"
      - "feat"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "bug"
      - "docs"
      - "chore"
  default: patch
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

# Auto-labeler para PRs con commits convencionales
autolabeler:
  - label: "feat"
    title:
      - '/^feat(\(.+\))?: .+/'
  - label: "fix"
    title:
      - '/^fix(\(.+\))?: .+/'
  - label: "docs"
    title:
      - '/^docs(\(.+\))?: .+/'
  - label: "chore"
    title:
      - '/^chore(\(.+\))?: .+/'
  - label: "refactor"
    title:
      - '/^refactor(\(.+\))?: .+/'
  - label: "test"
    title:
      - '/^test(\(.+\))?: .+/'
