name: Generate Changelog

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  changelog:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Generate and Commit Changelog
    # Only run if it's a push to main OR a merged PR to main
    if: github.ref == 'refs/heads/main' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        # Fetch full history for changelog generation
        fetch-depth: 0

    - name: Generate Changelog
      uses: smichard/conventional_changelog@2.0.10
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Git User Info
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'

    - name: Commit Changelog
      run: |
        git add CHANGELOG.md
        git commit -m "docs: :robot: changelog file generated" || echo "No changes to commit"
        git push
